name: Continuous Integration
on: [push, pull_request]

jobs:
  lint:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run 'make test'
        run: make test
