name: Linting
on: push

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run 'make lint'
        run: make lint
